#pragma once

#include "gd32h7xx.h"
#include "ring_buffer.h"
#include "uart.h"
#include <stdio.h>

#define CONSOLE_USARTX_MODE 0

#define CONSOLE_USARTX USART0
#define CONSOLE_USART_CLK RCU_USART0
#define CONSOLE_USART_BAUDRATE 115200
#define CONSOLE_USART_GPIO_APBXCLKCMD rcu_periph_clock_enable
#define CONSOLE_USART_GPIO_CLK_TX RCU_GPIOA
#define CONSOLE_USART_GPIO_CLK_RX RCU_GPIOA
#define CONSOLE_USART_TX_GPIO_PORT GPIOA
#define CONSOLE_USART_TX_GPIO_PIN GPIO_PIN_9
#define CONSOLE_USART_RX_GPIO_PORT GPIOA
#define CONSOLE_USART_RX_GPIO_PIN GPIO_PIN_10
#define CONSOLE_USART_TX_RX_GPIO_AF GPIO_AF_7
#define CONSOLE_TDATA_ADDRESS (&USART_TDATA(USART0))
#define CONSOLE_RDATA_ADDRESS (&USART_RDATA(USART0))
#define CONSOLE_USART_IRQ USART0_IRQn
#define CONSOLE_USART_IRQ_HANDLER USART0_IRQHandler
#define CONSOLE_DMA_TX_REQUEST DMA_REQUEST_USART0_TX
#define CONSOLE_DMA_RX_REQUEST DMA_REQUEST_USART0_RX

#define CONSOLE_DMA_BUFFER_RX_SIZE 20
#define CONSOLE_DMA_BUFFER_TX_SIZE 200

#define CONSOLE_RING_BUFFER_RX_SIZE 200
#define CONSOLE_RING_BUFFER_TX_SIZE 400

RING_BUFF_EXTERN(console_rx)
RING_BUFF_EXTERN(console_tx)

void console_init(void);
uart_handle_t* get_console(void);